# Generated by Django 2.2 on 2020-09-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='gender',
            field=models.CharField(default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='candidate',
            name='phone',
            field=models.CharField(default='0000000000', max_length=12),
        ),
    ]
