# Generated by Django 2.2 on 2020-09-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_auto_20200929_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
